happyhiking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('trails/', views.trails_index, name='trails_index'),
    path('trails/<int:trail_id>/', views.trails_detail, name='trails_detail'),
    path('trails/create/', views.TrailCreate.as_view(), name='trails_create'),
    path('trails/<int:pk>/update/', views.TrailUpdate.as_view(), name='trails_update'),
    path('trails/<int:pk>/delete/', views.TrailDelete.as_view(), name='trails_delete'),
    path('trails/<int:trail_id>/add_review/', views.add_review, name='add_review'),
    path('reviews/<int:review_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Trail(models.Model):
    name = models.CharField(max_length=75)
    description = models.TextField(max_length=400)
    length = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("trails_detail", kwargs={"trail_id": self.id})

EXPERIENCE = (
    ('B', 'Beginner'),
    ('I', 'Intermidiate'),
    ('E', 'Experienced'),
)

class Review(models.Model):
    date = models.DateField('Hike Date')
    text = models.TextField(max_length=500)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    difficulty = models.CharField(
        max_length=1,
        choices= EXPERIENCE,
        default=EXPERIENCE[0][0]
    )

    trail = models.ForeignKey(Trail, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_difficulty_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=250)
    review = models.OneToOneField(Review, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for review_id: {self.review_id} @{self.url}"

main_app/forms.py
from django.db.models.base import Model
from django.forms import ModelForm
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review 
        fields = ['date','text','difficulty', ]

main_app/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from .forms import ReviewForm
from .models import Trail, Review, Photo
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3

# Create your views here.
S3_BASE_URL = 'https://s3.us-west-1.amazonaws.com/'
BUCKET = 'happyhiking'
# Define the home view
@login_required
def add_photo(request, review_id):
  # photo-file will be the "name" attribute on the <input type="file">
  trails = Trail.objects.all()
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    # need a unique "key" for S3 / needs image file extension too
		# uuid.uuid4().hex generates a random hexadecimal Universally Unique Identifier
    # Add on the file extension using photo_file.name[photo_file.name.rfind('.'):]
    key = uuid.uuid4().hex + photo_file.name[photo_file.name.rfind('.'):]
    # just in case something goes wrong
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      # build the full url string
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      
      photo = Photo(url=url, review_id=review_id)
      # Remove old photo if it exists
      review_photo = Photo.objects.filter(review_id=review_id)
      if review_photo.first():
        review_photo.first().delete()
      photo.save()
    except Exception as err:
      print('An error occurred uploading file to S3: %s' % err)
  return render(request, 'trails/index.html', {'trails': trails})

class Home(LoginView):
  template_name = 'home.html'


def about(request):
    return render(request, 'about.html')

@login_required
def trails_index(request):
    trails = Trail.objects.filter(user=request.user)
    return render(request, 'trails/index.html', {'trails': trails})

@login_required
def trails_detail(request, trail_id):
    trail = Trail.objects.get(id=trail_id)
    review_form = ReviewForm()
    return render(request, 'trails/detail.html', {
        'trail': trail, 'review_form': review_form
        })

@login_required
def add_review(request, trail_id):
    form = ReviewForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.trail_id = trail_id
        new_review.save()
    return redirect('trails_detail', trail_id=trail_id)

class TrailCreate(LoginRequiredMixin, CreateView):
    model = Trail
    fields = ['name','length','description']

  
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class TrailUpdate(LoginRequiredMixin, UpdateView):
    model = Trail
    fields = ['length', 'description']

class TrailDelete(LoginRequiredMixin, DeleteView):
    model = Trail
    success_url = '/trails/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in
      login(request, user)
      return redirect('trails_index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}   

{% block content %}
<div class='about'>
  <h1>Benefits of Hiking</h1>
  <ul>
  <li>Exercise helps keep your body in the best shape possible</li>
  <li>Spending time in nature is shown to lower stress levels, as well as life overall mood
  <li>Helps maintain a healthy heart</li>
  </ul>
</div>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Hina+Mincho&display=swap" rel="stylesheet">
  <link
    rel="shortcut icon"
    type="image/png"
    href=""
  >
  <title>Happy Hiking</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <h1>Happy Hiking</h1>
    </div>
    <nav>
      <ul>
      {% if user.is_authenticated %}
        <li><a href="{% url 'trails_index' %}">Trails</a></li>
        <li><a href="{% url 'trails_create' %}">Add Trail</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'logout' %}">Log out</a></li>
      {% else %}
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'home' %}">Login</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
      {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}


{% block content %}

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
<section class="logo-container">
  <h1>Happy Hiking</h1>
  <img class='lil-mountain' src="{% static 'images/login-img.png' %}" alt="lil mountain">
</section>
{% endif %}

{% endblock %}

main_app/templates/main_app/trail_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Trail?</h1>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'trails_detail' trail.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/trail_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
    {% if object %}
    <h1>Edit {{ object.name }}</h1>
    {% else %}
    <h1>Add a Trail</h1>
    {% endif %}
    <img class='mtn-form' src="{% static 'images/mtn-form.png' %}" alt="A lil mountain"/>
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
    <h1>Sign Up</h1>
</div>
{% if error_message %}
    <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/trails/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/trail-detail.css' %}"
/>
<script defer src="{% static 'js/review-detail.js' %}"></script>
{% endblock %}

{% block content %}

<section class="trail-container">
  {% comment %} <div class="trail-img">
    {% if review.photo.url %}
      <img 
        src="{{review.photo.url}}" 
        alt="A photo of {{trail.name}}"
        class="usr-img"
      >
    {% else %}
      <img  
        alt="Upload did not work"
      >
    {% endif %}
  </div> {% endcomment %}
  <div class="trail-details">
    <h1>{{ trail.name }}</h1>
    <h3>{{ trail.length }} Miles</h3>
    <p>{{ trail.description }}</p>
    <div class="trail-actions">
      <a class='btn' href="{% url 'trails_update' trail.id %}">Update Trail</a>
      <a class='btn' href="{% url 'trails_delete' trail.id %}">Delete Trail</a>
    </div>
  </div>
</section>
<div class="reviews-container">
  <section class="reviews">
    <div class="subsection-title">
      <h3>Add Review</h3>
      <form 
      action="{% url 'add_review' trail.id %}"
      method='post'
      >
      {% csrf_token %}
      {{ review_form.as_p}}
      <button type='submit' >Add Review</button>
      </form>
      {% comment %} <div class='photo-form'>
    <h3>Change {{ trail.name }}'s photo</h3>
    <p id="file-name"></p>
    <form 
      action="{% url 'add_photo' trail.id %}"
      enctype="multipart/form-data"
      method="POST"
      
    >
      {% csrf_token %}
      <label class="btn secondary">
        Choose photo
        <input type="file" name="photo-file" id="file-input">
      </label>
      <button type="submit" class="btn submit">Upload Photo</button>
    </form>
      </div> {% endcomment %}
    </div>
    <div class='user-reviews'>
      <h2> Recent Reviews</h2>
    {% if trail.review_set.all.count %}
    <table>
      <thead>
        <tr><th>Date</th></tr>
      </thead>
      <tbody>
        {% for review in trail.review_set.all %}
          <tr>
            <td>{{review.date}}</td>
            
            </tr>
            <thead>
        <tr><th>Difficulty</th></tr>
            </thead>
            <tr>
            
            <td>{{review.get_difficulty_display}}</td>
            </tr>
          <thead>
        <tr><th>Review</th></tr>
          </thead>
          <tr>
            <td>{{review.text}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>Be the first to review {{ trail.name }}, add your experience above!</p>
    {% endif %}
    </div>
  </section>
</div>

{% endblock %}

main_app/templates/trails/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/trail-index.css' %}"/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Trail List</h1>
 

<section class="card-container">
  {% for trail in trails %}
    <div class="card">
    <a href="{% url 'trails_detail' trail.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img 
            src="{% static '' %}" 
            alt="picture of trail"
          >
        </div>
        <h2 class="card-title">{{ trail.name }}</h2>
        
        <p><small>{{ trail.description }}</small></p>
      </div>
    </a>
    </div>
  {% endfor %}
</section>

{% endblock %}